<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CardProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('order_items')->delete();
        \DB::table('card_products')->delete();

        \DB::table('card_products')->insert([
            [
                'card_number' => '1/163',
                'card_number_order' => 1,
                'card_url' => 'https://www.pokellector.com/card/Bellsprout-Battle-Styles-SWSH05-1',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 1,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Bellsprout.SWSH05.1.37528.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Bellsprout.SWSH05.1.37528.png',
                'name' => 'Bellsprout',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '2/163',
                'card_number_order' => 2,
                'card_url' => 'https://www.pokellector.com/card/Weepinbell-Battle-Styles-SWSH05-2',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 2,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Weepinbell.SWSH05.2.37529.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Weepinbell.SWSH05.2.37529.png',
                'name' => 'Weepinbell',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '3/163',
                'card_number_order' => 3,
                'card_url' => 'https://www.pokellector.com/card/Victreebel-Battle-Styles-SWSH05-3',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 3,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Victreebel.SWSH05.3.37530.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Victreebel.SWSH05.3.37530.png',
                'name' => 'Victreebel',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '4/163',
                'card_number_order' => 4,
                'card_url' => 'https://www.pokellector.com/card/Cacnea-Battle-Styles-SWSH05-4',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 4,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Cacnea.SWSH05.4.37531.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Cacnea.SWSH05.4.37531.png',
                'name' => 'Cacnea',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '5/163',
                'card_number_order' => 5,
                'card_url' => 'https://www.pokellector.com/card/Cacturne-Battle-Styles-SWSH05-5',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 5,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Cacturne.SWSH05.5.37532.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Cacturne.SWSH05.5.37532.png',
                'name' => 'Cacturne',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '6/163',
                'card_number_order' => 6,
                'card_url' => 'https://www.pokellector.com/card/Kricketune-V-Battle-Styles-SWSH05-6',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 6,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Kricketune-V.SWSH05.6.37533.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Kricketune-V.SWSH05.6.37533.png',
                'name' => 'Kricketune V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '7/163',
                'card_number_order' => 7,
                'card_url' => 'https://www.pokellector.com/card/Cherubi-Battle-Styles-SWSH05-7',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 7,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Cherubi.SWSH05.7.37534.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Cherubi.SWSH05.7.37534.png',
                'name' => 'Cherubi',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '8/163',
                'card_number_order' => 8,
                'card_url' => 'https://www.pokellector.com/card/Cherrim-Battle-Styles-SWSH05-8',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 8,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Cherrim.SWSH05.8.37535.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Cherrim.SWSH05.8.37535.png',
                'name' => 'Cherrim',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '9/163',
                'card_number_order' => 9,
                'card_url' => 'https://www.pokellector.com/card/Carnivine-Battle-Styles-SWSH05-9',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 9,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Carnivine.SWSH05.9.37536.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Carnivine.SWSH05.9.37536.png',
                'name' => 'Carnivine',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '10/163',
                'card_number_order' => 10,
                'card_url' => 'https://www.pokellector.com/card/Durant-Battle-Styles-SWSH05-10',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 10,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Durant.SWSH05.10.37537.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Durant.SWSH05.10.37537.png',
                'name' => 'Durant',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '11/163',
                'card_number_order' => 11,
                'card_url' => 'https://www.pokellector.com/card/Scatterbug-Battle-Styles-SWSH05-11',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 11,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Scatterbug.SWSH05.11.37538.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Scatterbug.SWSH05.11.37538.png',
                'name' => 'Scatterbug',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '12/163',
                'card_number_order' => 12,
                'card_url' => 'https://www.pokellector.com/card/Spewpa-Battle-Styles-SWSH05-12',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 12,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Spewpa.SWSH05.12.37539.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Spewpa.SWSH05.12.37539.png',
                'name' => 'Spewpa',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '13/163',
                'card_number_order' => 13,
                'card_url' => 'https://www.pokellector.com/card/Vivillon-Battle-Styles-SWSH05-13',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 13,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Vivillon.SWSH05.13.37540.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Vivillon.SWSH05.13.37540.png',
                'name' => 'Vivillon',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '14/163',
                'card_number_order' => 14,
                'card_url' => 'https://www.pokellector.com/card/Fomantis-Battle-Styles-SWSH05-14',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 14,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Fomantis.SWSH05.14.37541.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Fomantis.SWSH05.14.37541.png',
                'name' => 'Fomantis',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '15/163',
                'card_number_order' => 15,
                'card_url' => 'https://www.pokellector.com/card/Lurantis-Battle-Styles-SWSH05-15',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 15,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Lurantis.SWSH05.15.37542.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Lurantis.SWSH05.15.37542.png',
                'name' => 'Lurantis',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '16/163',
                'card_number_order' => 16,
                'card_url' => 'https://www.pokellector.com/card/Tapu-Bulu-Battle-Styles-SWSH05-16',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 16,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Tapu-Bulu.SWSH05.16.37543.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Tapu-Bulu.SWSH05.16.37543.png',
                'name' => 'Tapu Bulu',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '17/163',
                'card_number_order' => 17,
                'card_url' => 'https://www.pokellector.com/card/Blipbug-Battle-Styles-SWSH05-17',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 17,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Blipbug.SWSH05.17.37544.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Blipbug.SWSH05.17.37544.png',
                'name' => 'Blipbug',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '18/163',
                'card_number_order' => 18,
                'card_url' => 'https://www.pokellector.com/card/Flapple-V-Battle-Styles-SWSH05-18',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 18,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Flapple-V.SWSH05.18.37545.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Flapple-V.SWSH05.18.37545.png',
                'name' => 'Flapple V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '19/163',
                'card_number_order' => 19,
                'card_url' => 'https://www.pokellector.com/card/Flapple-VMAX-Battle-Styles-SWSH05-19',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 19,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Flapple-VMAX.SWSH05.19.37546.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Flapple-VMAX.SWSH05.19.37546.png',
                'name' => 'Flapple VMAX',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '20/163',
                'card_number_order' => 20,
                'card_url' => 'https://www.pokellector.com/card/Entei-Battle-Styles-SWSH05-20',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 20,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Entei.SWSH05.20.37547.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Entei.SWSH05.20.37547.png',
                'name' => 'Entei',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '21/163',
                'card_number_order' => 21,
                'card_url' => 'https://www.pokellector.com/card/Victini-V-Battle-Styles-SWSH05-21',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 21,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Victini-V.SWSH05.21.37548.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Victini-V.SWSH05.21.37548.png',
                'name' => 'Victini V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '22/163',
                'card_number_order' => 22,
                'card_url' => 'https://www.pokellector.com/card/Victini-VMAX-Battle-Styles-SWSH05-22',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 22,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Victini-VMAX.SWSH05.22.37549.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Victini-VMAX.SWSH05.22.37549.png',
                'name' => 'Victini VMAX',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '23/163',
                'card_number_order' => 23,
                'card_url' => 'https://www.pokellector.com/card/Tepig-Battle-Styles-SWSH05-23',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 23,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Tepig.SWSH05.23.37550.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Tepig.SWSH05.23.37550.png',
                'name' => 'Tepig',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '24/163',
                'card_number_order' => 24,
                'card_url' => 'https://www.pokellector.com/card/Pignite-Battle-Styles-SWSH05-24',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 24,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Pignite.SWSH05.24.37551.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Pignite.SWSH05.24.37551.png',
                'name' => 'Pignite',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:49',
            ],
            [
                'card_number' => '25/163',
                'card_number_order' => 25,
                'card_url' => 'https://www.pokellector.com/card/Emboar-Battle-Styles-SWSH05-25',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 25,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Emboar.SS5.25.36647.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Emboar.SS5.25.36647.png',
                'name' => 'Emboar',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '26/163',
                'card_number_order' => 26,
                'card_url' => 'https://www.pokellector.com/card/Heatmor-Battle-Styles-SWSH05-26',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 26,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Heatmor.SWSH05.26.37552.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Heatmor.SWSH05.26.37552.png',
                'name' => 'Heatmor',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '27/163',
                'card_number_order' => 27,
                'card_url' => 'https://www.pokellector.com/card/Salandit-Battle-Styles-SWSH05-27',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 27,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Salandit.SWSH05.27.37553.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Salandit.SWSH05.27.37553.png',
                'name' => 'Salandit',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '28/163',
                'card_number_order' => 28,
                'card_url' => 'https://www.pokellector.com/card/Salazzle-Battle-Styles-SWSH05-28',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 28,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Salazzle.SWSH05.28.37554.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Salazzle.SWSH05.28.37554.png',
                'name' => 'Salazzle',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '29/163',
                'card_number_order' => 29,
                'card_url' => 'https://www.pokellector.com/card/Sizzlipede-Battle-Styles-SWSH05-29',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 29,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Sizzlipede.SWSH05.29.37555.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Sizzlipede.SWSH05.29.37555.png',
                'name' => 'Sizzlipede',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '30/163',
                'card_number_order' => 30,
                'card_url' => 'https://www.pokellector.com/card/Centiskorch-Battle-Styles-SWSH05-30',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 30,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Centiskorch.SWSH05.30.37556.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Centiskorch.SWSH05.30.37556.png',
                'name' => 'Centiskorch',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '31/163',
                'card_number_order' => 31,
                'card_url' => 'https://www.pokellector.com/card/Horsea-Battle-Styles-SWSH05-31',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 31,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Horsea.SWSH05.31.37557.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Horsea.SWSH05.31.37557.png',
                'name' => 'Horsea',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '32/163',
                'card_number_order' => 32,
                'card_url' => 'https://www.pokellector.com/card/Seadra-Battle-Styles-SWSH05-32',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 32,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Seadra.SWSH05.32.37558.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Seadra.SWSH05.32.37558.png',
                'name' => 'Seadra',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '33/163',
                'card_number_order' => 33,
                'card_url' => 'https://www.pokellector.com/card/Kingdra-Battle-Styles-SWSH05-33',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 33,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Kingdra.SWSH05.33.37559.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Kingdra.SWSH05.33.37559.png',
                'name' => 'Kingdra',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '34/163',
                'card_number_order' => 34,
                'card_url' => 'https://www.pokellector.com/card/Galarian-Mr-Mime-Battle-Styles-SWSH05-34',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 34,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Galarian-Mr-Mime.SWSH05.34.37560.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Galarian-Mr-Mime.SWSH05.34.37560.png',
                'name' => 'Galarian Mr. Mime',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '35/163',
                'card_number_order' => 35,
                'card_url' => 'https://www.pokellector.com/card/Galarian-Mr-Rime-Battle-Styles-SWSH05-35',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 35,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Galarian-Mr-Rime.SWSH05.35.37561.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Galarian-Mr-Rime.SWSH05.35.37561.png',
                'name' => 'Galarian Mr. Rime',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '36/163',
                'card_number_order' => 36,
                'card_url' => 'https://www.pokellector.com/card/Remoraid-Battle-Styles-SWSH05-36',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 36,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Remoraid.SWSH05.36.37562.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Remoraid.SWSH05.36.37562.png',
                'name' => 'Remoraid',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '37/163',
                'card_number_order' => 37,
                'card_url' => 'https://www.pokellector.com/card/Octillery-Battle-Styles-SWSH05-37',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 37,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Octillery.SS5.37.36648.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Octillery.SS5.37.36648.png',
                'name' => 'Octillery',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '38/163',
                'card_number_order' => 38,
                'card_url' => 'https://www.pokellector.com/card/Corphish-Battle-Styles-SWSH05-38',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 38,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Corphish.SWSH05.38.37563.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Corphish.SWSH05.38.37563.png',
                'name' => 'Corphish',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '39/163',
                'card_number_order' => 39,
                'card_url' => 'https://www.pokellector.com/card/Crawdaunt-Battle-Styles-SWSH05-39',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 39,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Crawdaunt.SWSH05.39.37564.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Crawdaunt.SWSH05.39.37564.png',
                'name' => 'Crawdaunt',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '40/163',
                'card_number_order' => 40,
                'card_url' => 'https://www.pokellector.com/card/Empoleon-V-Battle-Styles-SWSH05-40',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 40,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Empoleon-V.SS5.40.36649.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Empoleon-V.SS5.40.36649.png',
                'name' => 'Empoleon V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '41/163',
                'card_number_order' => 41,
                'card_url' => 'https://www.pokellector.com/card/Frillish-Battle-Styles-SWSH05-41',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 41,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Frillish.SWSH05.41.37565.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Frillish.SWSH05.41.37565.png',
                'name' => 'Frillish',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '42/163',
                'card_number_order' => 42,
                'card_url' => 'https://www.pokellector.com/card/Jellicent-Battle-Styles-SWSH05-42',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 42,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Jellicent.SWSH05.42.37566.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Jellicent.SWSH05.42.37566.png',
                'name' => 'Jellicent',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '43/163',
                'card_number_order' => 43,
                'card_url' => 'https://www.pokellector.com/card/Bruxish-Battle-Styles-SWSH05-43',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 43,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Bruxish.SWSH05.43.37567.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Bruxish.SWSH05.43.37567.png',
                'name' => 'Bruxish',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '44/163',
                'card_number_order' => 44,
                'card_url' => 'https://www.pokellector.com/card/Electabuzz-Battle-Styles-SWSH05-44',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 44,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Electabuzz.SWSH05.44.37568.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Electabuzz.SWSH05.44.37568.png',
                'name' => 'Electabuzz',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '45/163',
                'card_number_order' => 45,
                'card_url' => 'https://www.pokellector.com/card/Electivire-Battle-Styles-SWSH05-45',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 45,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Electivire.SWSH05.45.37569.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Electivire.SWSH05.45.37569.png',
                'name' => 'Electivire',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '46/163',
                'card_number_order' => 46,
                'card_url' => 'https://www.pokellector.com/card/Shinx-Battle-Styles-SWSH05-46',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 46,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Shinx.SWSH05.46.37570.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Shinx.SWSH05.46.37570.png',
                'name' => 'Shinx',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '47/163',
                'card_number_order' => 47,
                'card_url' => 'https://www.pokellector.com/card/Luxio-Battle-Styles-SWSH05-47',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 47,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Luxio.SWSH05.47.37571.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Luxio.SWSH05.47.37571.png',
                'name' => 'Luxio',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '48/163',
                'card_number_order' => 48,
                'card_url' => 'https://www.pokellector.com/card/Luxray-Battle-Styles-SWSH05-48',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 48,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Luxray.SWSH05.48.37572.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Luxray.SWSH05.48.37572.png',
                'name' => 'Luxray',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '49/163',
                'card_number_order' => 49,
                'card_url' => 'https://www.pokellector.com/card/Pachirisu-Battle-Styles-SWSH05-49',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 49,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Pachirisu.SWSH05.49.37573.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Pachirisu.SWSH05.49.37573.png',
                'name' => 'Pachirisu',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '50/163',
                'card_number_order' => 50,
                'card_url' => 'https://www.pokellector.com/card/Tapu-Koko-V-Battle-Styles-SWSH05-50',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 50,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Tapu-Koko-V.SWSH05.50.37574.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Tapu-Koko-V.SWSH05.50.37574.png',
                'name' => 'Tapu Koko V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '51/163',
                'card_number_order' => 51,
                'card_url' => 'https://www.pokellector.com/card/Tapu-Koko-VMAX-Battle-Styles-SWSH05-51',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 51,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Tapu-Koko-VMAX.SWSH05.51.37575.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Tapu-Koko-VMAX.SWSH05.51.37575.png',
                'name' => 'Tapu Koko VMAX',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '52/163',
                'card_number_order' => 52,
                'card_url' => 'https://www.pokellector.com/card/Yamper-Battle-Styles-SWSH05-52',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 52,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Yamper.SWSH05.52.37576.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Yamper.SWSH05.52.37576.png',
                'name' => 'Yamper',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '53/163',
                'card_number_order' => 53,
                'card_url' => 'https://www.pokellector.com/card/Boltund-Battle-Styles-SWSH05-53',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 53,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Boltund.SWSH05.53.37577.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Boltund.SWSH05.53.37577.png',
                'name' => 'Boltund',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '54/163',
                'card_number_order' => 54,
                'card_url' => 'https://www.pokellector.com/card/Galarian-Slowpoke-Battle-Styles-SWSH05-54',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 54,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Galarian-Slowpoke.SWSH05.54.37578.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Galarian-Slowpoke.SWSH05.54.37578.png',
                'name' => 'Galarian Slowpoke',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '55/163',
                'card_number_order' => 55,
                'card_url' => 'https://www.pokellector.com/card/Spoink-Battle-Styles-SWSH05-55',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 55,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Spoink.SWSH05.55.37579.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Spoink.SWSH05.55.37579.png',
                'name' => 'Spoink',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '56/163',
                'card_number_order' => 56,
                'card_url' => 'https://www.pokellector.com/card/Grumpig-Battle-Styles-SWSH05-56',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 56,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Grumpig.SWSH05.56.37580.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Grumpig.SWSH05.56.37580.png',
                'name' => 'Grumpig',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '57/163',
                'card_number_order' => 57,
                'card_url' => 'https://www.pokellector.com/card/Baltoy-Battle-Styles-SWSH05-57',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 57,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Baltoy.SWSH05.57.37581.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Baltoy.SWSH05.57.37581.png',
                'name' => 'Baltoy',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '58/163',
                'card_number_order' => 58,
                'card_url' => 'https://www.pokellector.com/card/Claydol-Battle-Styles-SWSH05-58',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 58,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Claydol.SWSH05.58.37582.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Claydol.SWSH05.58.37582.png',
                'name' => 'Claydol',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '59/163',
                'card_number_order' => 59,
                'card_url' => 'https://www.pokellector.com/card/Chimecho-Battle-Styles-SWSH05-59',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 59,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Chimecho.SWSH05.59.37583.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Chimecho.SWSH05.59.37583.png',
                'name' => 'Chimecho',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '60/163',
                'card_number_order' => 60,
                'card_url' => 'https://www.pokellector.com/card/Espurr-Battle-Styles-SWSH05-60',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 60,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Espurr.SWSH05.60.37584.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Espurr.SWSH05.60.37584.png',
                'name' => 'Espurr',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '61/163',
                'card_number_order' => 61,
                'card_url' => 'https://www.pokellector.com/card/Meowstic-Battle-Styles-SWSH05-61',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 61,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Meowstic.SWSH05.61.37585.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Meowstic.SWSH05.61.37585.png',
                'name' => 'Meowstic',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '62/163',
                'card_number_order' => 62,
                'card_url' => 'https://www.pokellector.com/card/Mimikyu-V-Battle-Styles-SWSH05-62',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 62,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Mimikyu-V.SWSH05.62.37586.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Mimikyu-V.SWSH05.62.37586.png',
                'name' => 'Mimikyu V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '63/163',
                'card_number_order' => 63,
                'card_url' => 'https://www.pokellector.com/card/Necrozma-V-Battle-Styles-SWSH05-63',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 63,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Necrozma-V.SWSH05.63.37587.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Necrozma-V.SWSH05.63.37587.png',
                'name' => 'Necrozma V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '64/163',
                'card_number_order' => 64,
                'card_url' => 'https://www.pokellector.com/card/Dottler-Battle-Styles-SWSH05-64',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 64,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Dottler.SWSH05.64.37588.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Dottler.SWSH05.64.37588.png',
                'name' => 'Dottler',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '65/163',
                'card_number_order' => 65,
                'card_url' => 'https://www.pokellector.com/card/Orbeetle-Battle-Styles-SWSH05-65',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 65,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Orbeetle.SWSH05.65.37589.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Orbeetle.SWSH05.65.37589.png',
                'name' => 'Orbeetle',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:50',
            ],
            [
                'card_number' => '66/163',
                'card_number_order' => 66,
                'card_url' => 'https://www.pokellector.com/card/Mankey-Battle-Styles-SWSH05-66',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 66,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Mankey.SWSH05.66.37590.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Mankey.SWSH05.66.37590.png',
                'name' => 'Mankey',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '67/163',
                'card_number_order' => 67,
                'card_url' => 'https://www.pokellector.com/card/Primeape-Battle-Styles-SWSH05-67',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 67,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Primeape.SWSH05.67.37591.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Primeape.SWSH05.67.37591.png',
                'name' => 'Primeape',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '68/163',
                'card_number_order' => 68,
                'card_url' => 'https://www.pokellector.com/card/Onix-Battle-Styles-SWSH05-68',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 68,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Onix.SWSH05.68.37592.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Onix.SWSH05.68.37592.png',
                'name' => 'Onix',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '69/163',
                'card_number_order' => 69,
                'card_url' => 'https://www.pokellector.com/card/Cubone-Battle-Styles-SWSH05-69',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 69,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Cubone.SWSH05.69.37593.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Cubone.SWSH05.69.37593.png',
                'name' => 'Cubone',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '70/163',
                'card_number_order' => 70,
                'card_url' => 'https://www.pokellector.com/card/Marowak-Battle-Styles-SWSH05-70',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 70,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Marowak.SWSH05.70.37594.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Marowak.SWSH05.70.37594.png',
                'name' => 'Marowak',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '71/163',
                'card_number_order' => 71,
                'card_url' => 'https://www.pokellector.com/card/Gligar-Battle-Styles-SWSH05-71',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 71,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Gligar.SWSH05.71.37595.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Gligar.SWSH05.71.37595.png',
                'name' => 'Gligar',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '72/163',
                'card_number_order' => 72,
                'card_url' => 'https://www.pokellector.com/card/Gliscor-Battle-Styles-SWSH05-72',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 72,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Gliscor.SWSH05.72.37596.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Gliscor.SWSH05.72.37596.png',
                'name' => 'Gliscor',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '73/163',
                'card_number_order' => 73,
                'card_url' => 'https://www.pokellector.com/card/Timburr-Battle-Styles-SWSH05-73',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 73,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Timburr.SWSH05.73.37597.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Timburr.SWSH05.73.37597.png',
                'name' => 'Timburr',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '74/163',
                'card_number_order' => 74,
                'card_url' => 'https://www.pokellector.com/card/Gurdurr-Battle-Styles-SWSH05-74',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 74,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Gurdurr.SWSH05.74.37598.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Gurdurr.SWSH05.74.37598.png',
                'name' => 'Gurdurr',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '75/163',
                'card_number_order' => 75,
                'card_url' => 'https://www.pokellector.com/card/Conkeldurr-Battle-Styles-SWSH05-75',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 75,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Conkeldurr.SWSH05.75.37599.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Conkeldurr.SWSH05.75.37599.png',
                'name' => 'Conkeldurr',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '76/163',
                'card_number_order' => 76,
                'card_url' => 'https://www.pokellector.com/card/Mienfoo-Battle-Styles-SWSH05-76',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 76,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Mienfoo.SWSH05.76.37600.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Mienfoo.SWSH05.76.37600.png',
                'name' => 'Mienfoo',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '77/163',
                'card_number_order' => 77,
                'card_url' => 'https://www.pokellector.com/card/Mienshao-Battle-Styles-SWSH05-77',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 77,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Mienshao.SS5.77.36650.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Mienshao.SS5.77.36650.png',
                'name' => 'Mienshao',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '78/163',
                'card_number_order' => 78,
                'card_url' => 'https://www.pokellector.com/card/Rolycoly-Battle-Styles-SWSH05-78',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 78,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Rolycoly.SWSH05.78.37601.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Rolycoly.SWSH05.78.37601.png',
                'name' => 'Rolycoly',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '79/163',
                'card_number_order' => 79,
                'card_url' => 'https://www.pokellector.com/card/Carkol-Battle-Styles-SWSH05-79',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 79,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Carkol.SWSH05.79.37602.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Carkol.SWSH05.79.37602.png',
                'name' => 'Carkol',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '80/163',
                'card_number_order' => 80,
                'card_url' => 'https://www.pokellector.com/card/Coalossal-Battle-Styles-SWSH05-80',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 80,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Coalossal.SWSH05.80.37603.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Coalossal.SWSH05.80.37603.png',
                'name' => 'Coalossal',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '81/163',
                'card_number_order' => 81,
                'card_url' => 'https://www.pokellector.com/card/Silicobra-Battle-Styles-SWSH05-81',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 81,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Silicobra.SWSH05.81.37604.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Silicobra.SWSH05.81.37604.png',
                'name' => 'Silicobra',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '82/163',
                'card_number_order' => 82,
                'card_url' => 'https://www.pokellector.com/card/Sandaconda-Battle-Styles-SWSH05-82',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 82,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Sandaconda.SWSH05.82.37605.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Sandaconda.SWSH05.82.37605.png',
                'name' => 'Sandaconda',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '83/163',
                'card_number_order' => 83,
                'card_url' => 'https://www.pokellector.com/card/Falinks-Battle-Styles-SWSH05-83',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 83,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Falinks.SWSH05.83.37606.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Falinks.SWSH05.83.37606.png',
                'name' => 'Falinks',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '84/163',
                'card_number_order' => 84,
                'card_url' => 'https://www.pokellector.com/card/Stonjourner-Battle-Styles-SWSH05-84',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 84,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Stonjourner.SWSH05.84.37607.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Stonjourner.SWSH05.84.37607.png',
                'name' => 'Stonjourner',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '85/163',
                'card_number_order' => 85,
                'card_url' => 'https://www.pokellector.com/card/Single-Strike-Urshifu-V-Battle-Styles-SWSH05-85',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 85,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Single-Strike-Urshifu-V.SS5.85.36651.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Single-Strike-Urshifu-V.SS5.85.36651.png',
                'name' => 'Single Strike Urshifu V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '86/163',
                'card_number_order' => 86,
                'card_url' => 'https://www.pokellector.com/card/Single-Strike-Urshifu-VMAX-Battle-Styles-SWSH05-86',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 86,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Single-Strike-Urshifu-VMAX.SS5.86.36652.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Single-Strike-Urshifu-VMAX.SS5.86.36652.png',
                'name' => 'Single Strike Urshifu VMAX',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '87/163',
                'card_number_order' => 87,
                'card_url' => 'https://www.pokellector.com/card/Rapid-Strike-Urshifu-V-Battle-Styles-SWSH05-87',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 87,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Rapid-Strike-Urshifu-V.SS5.87.36645.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Rapid-Strike-Urshifu-V.SS5.87.36645.png',
                'name' => 'Rapid Strike Urshifu V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '88/163',
                'card_number_order' => 88,
                'card_url' => 'https://www.pokellector.com/card/Rapid-Strike-Urshifu-VMAX-Battle-Styles-SWSH05-88',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 88,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Rapid-Strike-Urshifu-VMAX.SS5.88.36653.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Rapid-Strike-Urshifu-VMAX.SS5.88.36653.png',
                'name' => 'Rapid Strike Urshifu VMAX',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '89/163',
                'card_number_order' => 89,
                'card_url' => 'https://www.pokellector.com/card/Zubat-Battle-Styles-SWSH05-89',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 89,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Zubat.SWSH05.89.37608.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Zubat.SWSH05.89.37608.png',
                'name' => 'Zubat',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '90/163',
                'card_number_order' => 90,
                'card_url' => 'https://www.pokellector.com/card/Golbat-Battle-Styles-SWSH05-90',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 90,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Golbat.SWSH05.90.37609.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Golbat.SWSH05.90.37609.png',
                'name' => 'Golbat',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '91/163',
                'card_number_order' => 91,
                'card_url' => 'https://www.pokellector.com/card/Crobat-Battle-Styles-SWSH05-91',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 91,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Crobat.SWSH05.91.37610.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Crobat.SWSH05.91.37610.png',
                'name' => 'Crobat',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '92/163',
                'card_number_order' => 92,
                'card_url' => 'https://www.pokellector.com/card/Galarian-Slowbro-Battle-Styles-SWSH05-92',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 92,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Galarian-Slowbro.SWSH05.92.37611.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Galarian-Slowbro.SWSH05.92.37611.png',
                'name' => 'Galarian Slowbro',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '93/163',
                'card_number_order' => 93,
                'card_url' => 'https://www.pokellector.com/card/Murkrow-Battle-Styles-SWSH05-93',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 93,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Murkrow.SWSH05.93.37612.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Murkrow.SWSH05.93.37612.png',
                'name' => 'Murkrow',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '94/163',
                'card_number_order' => 94,
                'card_url' => 'https://www.pokellector.com/card/Honchkrow-Battle-Styles-SWSH05-94',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 94,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Honchkrow.SWSH05.94.37613.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Honchkrow.SWSH05.94.37613.png',
                'name' => 'Honchkrow',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '95/163',
                'card_number_order' => 95,
                'card_url' => 'https://www.pokellector.com/card/Houndour-Battle-Styles-SWSH05-95',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 95,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Houndour.SWSH05.95.37614.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Houndour.SWSH05.95.37614.png',
                'name' => 'Houndour',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '96/163',
                'card_number_order' => 96,
                'card_url' => 'https://www.pokellector.com/card/Houndoom-Battle-Styles-SWSH05-96',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 96,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Houndoom.SS5.96.36646.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Houndoom.SS5.96.36646.png',
                'name' => 'Houndoom',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '97/163',
                'card_number_order' => 97,
                'card_url' => 'https://www.pokellector.com/card/Tyranitar-V-Battle-Styles-SWSH05-97',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 97,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Tyranitar-V.SS5.97.36654.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Tyranitar-V.SS5.97.36654.png',
                'name' => 'Tyranitar V',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '98/163',
                'card_number_order' => 98,
                'card_url' => 'https://www.pokellector.com/card/Morpeko-Battle-Styles-SWSH05-98',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 98,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Morpeko.SWSH05.98.37615.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Morpeko.SWSH05.98.37615.png',
                'name' => 'Morpeko',
                'rarity' => 'Uncommon',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '99/163',
                'card_number_order' => 99,
                'card_url' => 'https://www.pokellector.com/card/Steelix-Battle-Styles-SWSH05-99',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 99,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Steelix.SWSH05.99.37616.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Steelix.SWSH05.99.37616.png',
                'name' => 'Steelix',
                'rarity' => 'Rare',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
            [
                'card_number' => '100/163',
                'card_number_order' => 100,
                'card_url' => 'https://www.pokellector.com/card/Mawile-Battle-Styles-SWSH05-100',
                'card_category_id' => 1,
                'created_at' => '2021-08-07 19:16:15',
                'id' => 100,
                'image_bucket_path' => 's3://wooter-ags-database-cards/pokemon_cards_images/cards_images/Mawile.SWSH05.100.37617.png',
                'image_path' => 'https://den-cards.pokellector.com/305/Mawile.SWSH05.100.37617.png',
                'name' => 'Mawile',
                'rarity' => 'Common',
                'card_set_id' => 1,
                'updated_at' => '2021-08-07 20:27:51',
            ],
        ]);
    }
}
