<?php

use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $now = now();

        DB::table('countries')->insert([
            ['code' => 'AF', 'name' => 'Afghanistan', 'phone_code' => '93', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AL', 'name' => 'Albania', 'phone_code' => '355', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'DZ', 'name' => 'Algeria', 'phone_code' => '213', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AD', 'name' => 'Andorra', 'phone_code' => '376', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AO', 'name' => 'Angola', 'phone_code' => '244', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AG', 'name' => 'Antigua And Barbuda', 'phone_code' => '1268', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AR', 'name' => 'Argentina', 'phone_code' => '54', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AM', 'name' => 'Armenia', 'phone_code' => '374', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AW', 'name' => 'Aruba', 'phone_code' => '297', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AT', 'name' => 'Austria', 'phone_code' => '43', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'phone_code' => '994', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BS', 'name' => 'Bahamas', 'phone_code' => '1242', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BH', 'name' => 'Bahrain', 'phone_code' => '973', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BD', 'name' => 'Bangladesh', 'phone_code' => '880', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BB', 'name' => 'Barbados', 'phone_code' => '1246', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BE', 'name' => 'Belgium', 'phone_code' => '32', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BZ', 'name' => 'Belize', 'phone_code' => '501', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BJ', 'name' => 'Benin', 'phone_code' => '229', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BT', 'name' => 'Bhutan', 'phone_code' => '975', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BO', 'name' => 'Bolivia', 'phone_code' => '591', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BA', 'name' => 'Bosnia And Herzegovina', 'phone_code' => '387', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BW', 'name' => 'Botswana', 'phone_code' => '267', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BR', 'name' => 'Brazil', 'phone_code' => '55', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BN', 'name' => 'Brunei Darussalam', 'phone_code' => '673', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BG', 'name' => 'Bulgaria', 'phone_code' => '359', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'phone_code' => '226', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'BI', 'name' => 'Burundi', 'phone_code' => '257', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KH', 'name' => 'Cambodia', 'phone_code' => '855', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CM', 'name' => 'Cameroon', 'phone_code' => '237', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CV', 'name' => 'Cape Verde', 'phone_code' => '238', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CF', 'name' => 'Central African Republic', 'phone_code' => '236', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TD', 'name' => 'Chad', 'phone_code' => '235', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CL', 'name' => 'Chile', 'phone_code' => '56', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CN', 'name' => 'China', 'phone_code' => '86', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CO', 'name' => 'Colombia', 'phone_code' => '57', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KM', 'name' => 'Comoros', 'phone_code' => '269', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CG', 'name' => 'Congo', 'phone_code' => '242', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CR', 'name' => 'Costa Rica', 'phone_code' => '506', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'HR', 'name' => 'Croatia', 'phone_code' => '385', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CU', 'name' => 'Cuba', 'phone_code' => '53', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CW', 'name' => 'Curacao', 'phone_code' => '599', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CY', 'name' => 'Cyprus', 'phone_code' => '357', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'phone_code' => '420', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'DK', 'name' => 'Denmark', 'phone_code' => '45', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'DJ', 'name' => 'Djibouti', 'phone_code' => '253', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'DM', 'name' => 'Dominica', 'phone_code' => '1767', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'phone_code' => '1', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'EC', 'name' => 'Ecuador', 'phone_code' => '593', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'EG', 'name' => 'Egypt', 'phone_code' => '20', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SV', 'name' => 'El Salvador', 'phone_code' => '503', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'phone_code' => '240', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ER', 'name' => 'Eritrea', 'phone_code' => '291', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'EE', 'name' => 'Estonia', 'phone_code' => '372', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ET', 'name' => 'Ethiopia', 'phone_code' => '251', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'FJ', 'name' => 'Fiji', 'phone_code' => '679', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'FI', 'name' => 'Finland', 'phone_code' => '358', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GF', 'name' => 'French Guiana', 'phone_code' => '594', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PF', 'name' => 'French Polynesia', 'phone_code' => '689', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GA', 'name' => 'Gabon', 'phone_code' => '241', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GM', 'name' => 'Gambia', 'phone_code' => '220', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GE', 'name' => 'Georgia', 'phone_code' => '995', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GH', 'name' => 'Ghana', 'phone_code' => '233', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GR', 'name' => 'Greece', 'phone_code' => '30', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GD', 'name' => 'Grenada', 'phone_code' => '1473', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'phone_code' => '590', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GU', 'name' => 'Guam', 'phone_code' => '1671', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GT', 'name' => 'Guatemala', 'phone_code' => '502', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GW', 'name' => 'Guinea-bissau', 'phone_code' => '245', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'GY', 'name' => 'Guyana', 'phone_code' => '592', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'HT', 'name' => 'Haiti', 'phone_code' => '509', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'HN', 'name' => 'Honduras', 'phone_code' => '504', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'HK', 'name' => 'Hong Kong', 'phone_code' => '852', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'HU', 'name' => 'Hungary', 'phone_code' => '36', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'IS', 'name' => 'Iceland', 'phone_code' => '354', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'IN', 'name' => 'India', 'phone_code' => '91', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ID', 'name' => 'Indonesia', 'phone_code' => '62', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'IR', 'name' => 'Iran', 'phone_code' => '98', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'IQ', 'name' => 'Iraq', 'phone_code' => '964', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'IE', 'name' => 'Ireland', 'phone_code' => '353', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'IL', 'name' => 'Israel', 'phone_code' => '972', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'IT', 'name' => 'Italy', 'phone_code' => '39', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'JM', 'name' => 'Jamaica', 'phone_code' => '1876', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'JO', 'name' => 'Jordan', 'phone_code' => '962', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'phone_code' => '7', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KE', 'name' => 'Kenya', 'phone_code' => '254', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KI', 'name' => 'Kiribati', 'phone_code' => '686', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KW', 'name' => 'Kuwait', 'phone_code' => '965', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'phone_code' => '996', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LA', 'name' => 'Laos', 'phone_code' => '856', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LV', 'name' => 'Latvia', 'phone_code' => '371', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LB', 'name' => 'Lebanon', 'phone_code' => '961', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LS', 'name' => 'Lesotho', 'phone_code' => '266', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LR', 'name' => 'Liberia', 'phone_code' => '231', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LY', 'name' => 'Libya', 'phone_code' => '218', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'phone_code' => '423', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LT', 'name' => 'Lithuania', 'phone_code' => '370', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LU', 'name' => 'Luxembourg', 'phone_code' => '352', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MK', 'name' => 'Macedonia', 'phone_code' => '389', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MG', 'name' => 'Madagascar', 'phone_code' => '261', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MW', 'name' => 'Malawi', 'phone_code' => '265', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MY', 'name' => 'Malaysia', 'phone_code' => '60', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MV', 'name' => 'Maldives', 'phone_code' => '960', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ML', 'name' => 'Mali', 'phone_code' => '223', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MT', 'name' => 'Malta', 'phone_code' => '356', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MQ', 'name' => 'Martinique', 'phone_code' => '596', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MR', 'name' => 'Mauritania', 'phone_code' => '222', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MU', 'name' => 'Mauritius', 'phone_code' => '230', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MD', 'name' => 'Moldova', 'phone_code' => '373', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MX', 'name' => 'Mexico', 'phone_code' => '52', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MC', 'name' => 'Monaco', 'phone_code' => '377', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MN', 'name' => 'Mongolia', 'phone_code' => '976', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ME', 'name' => 'Montenegro', 'phone_code' => '382', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MA', 'name' => 'Morocco', 'phone_code' => '212', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MZ', 'name' => 'Mozambique', 'phone_code' => '258', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'MM', 'name' => 'Myanmar', 'phone_code' => '95', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NA', 'name' => 'Namibia', 'phone_code' => '264', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NR', 'name' => 'Nauru', 'phone_code' => '674', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NP', 'name' => 'Nepal', 'phone_code' => '977', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NL', 'name' => 'Netherlands', 'phone_code' => '31', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NC', 'name' => 'New Caledonia', 'phone_code' => '687', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NZ', 'name' => 'New Zealand', 'phone_code' => '64', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NI', 'name' => 'Nicaragua', 'phone_code' => '505', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NE', 'name' => 'Niger', 'phone_code' => '227', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NG', 'name' => 'Nigeria', 'phone_code' => '234', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KP', 'name' => 'North Korea', 'phone_code' => '850', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'NO', 'name' => 'Norway', 'phone_code' => '47', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'OM', 'name' => 'Oman', 'phone_code' => '968', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PK', 'name' => 'Pakistan', 'phone_code' => '92', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PW', 'name' => 'Palau', 'phone_code' => '680', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PS', 'name' => 'Palestine', 'phone_code' => '970', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PA', 'name' => 'Panama', 'phone_code' => '507', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'phone_code' => '675', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PY', 'name' => 'Paraguay', 'phone_code' => '595', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PE', 'name' => 'Peru', 'phone_code' => '51', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PH', 'name' => 'Philippines', 'phone_code' => '63', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PL', 'name' => 'Poland', 'phone_code' => '48', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PT', 'name' => 'Portugal', 'phone_code' => '351', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'phone_code' => '1', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'QA', 'name' => 'Qatar', 'phone_code' => '974', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'RO', 'name' => 'Romania', 'phone_code' => '40', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'RW', 'name' => 'Rwanda', 'phone_code' => '250', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'RE', 'name' => 'Reunion', 'phone_code' => '262', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KN', 'name' => 'Saint Kitts And Nevis', 'phone_code' => '1869', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'phone_code' => '1758', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'VC', 'name' => 'Saint Vincent And The Grenadines', 'phone_code' => '1784', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'WS', 'name' => 'Samoa', 'phone_code' => '685', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SM', 'name' => 'San Marino', 'phone_code' => '378', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ST', 'name' => 'Sao Tome And Principe', 'phone_code' => '239', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'phone_code' => '966', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SN', 'name' => 'Senegal', 'phone_code' => '221', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'RS', 'name' => 'Serbia', 'phone_code' => '381', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SC', 'name' => 'Seychelles', 'phone_code' => '248', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'phone_code' => '232', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SG', 'name' => 'Singapore', 'phone_code' => '65', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SK', 'name' => 'Slovakia', 'phone_code' => '421', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SI', 'name' => 'Slovenia', 'phone_code' => '386', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'phone_code' => '677', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SO', 'name' => 'Somalia', 'phone_code' => '252', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ZA', 'name' => 'South Africa', 'phone_code' => '27', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'KR', 'name' => 'South Korea', 'phone_code' => '82', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SS', 'name' => 'South Sudan', 'phone_code' => '211', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'phone_code' => '94', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SD', 'name' => 'Sudan', 'phone_code' => '249', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SR', 'name' => 'Suriname', 'phone_code' => '597', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SZ', 'name' => 'Swaziland', 'phone_code' => '268', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SE', 'name' => 'Sweden', 'phone_code' => '46', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CH', 'name' => 'Switzerland', 'phone_code' => '41', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'SY', 'name' => 'Syria', 'phone_code' => '963', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TW', 'name' => 'Taiwan', 'phone_code' => '886', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'phone_code' => '992', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TZ', 'name' => 'Tanzania', 'phone_code' => '255', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TH', 'name' => 'Thailand', 'phone_code' => '66', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TL', 'name' => 'Timor-leste', 'phone_code' => '670', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TG', 'name' => 'Togo', 'phone_code' => '228', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TO', 'name' => 'Tonga', 'phone_code' => '676', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TT', 'name' => 'Trinidad And Tobago', 'phone_code' => '1868', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TN', 'name' => 'Tunisia', 'phone_code' => '216', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TR', 'name' => 'Turkey', 'phone_code' => '90', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'phone_code' => '993', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'TV', 'name' => 'Tuvalu', 'phone_code' => '688', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'UG', 'name' => 'Uganda', 'phone_code' => '256', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'phone_code' => '971', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'UY', 'name' => 'Uruguay', 'phone_code' => '598', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'phone_code' => '998', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'VU', 'name' => 'Vanuatu', 'phone_code' => '678', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'VE', 'name' => 'Venezuela', 'phone_code' => '58', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'VN', 'name' => 'Vietnam', 'phone_code' => '84', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'VA', 'name' => 'Vatican City', 'phone_code' => '379', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'YE', 'name' => 'Yemen', 'phone_code' => '967', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ZM', 'name' => 'Zambia', 'phone_code' => '260', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'phone_code' => '263', 'is_enabled' => 1, 'created_at' => $now, 'updated_at' => $now],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('countries')->whereIn('code', [
            'AF',
            'AL',
            'DZ',
            'AD',
            'AO',
            'AG',
            'AR',
            'AM',
            'AW',
            'AT',
            'AZ',
            'BS',
            'BH',
            'BD',
            'BB',
            'BE',
            'BZ',
            'BJ',
            'BT',
            'BO',
            'BA',
            'BW',
            'BR',
            'BN',
            'BG',
            'BF',
            'BI',
            'KH',
            'CM',
            'CV',
            'CF',
            'TD',
            'CL',
            'CN',
            'CO',
            'KM',
            'CG',
            'CR',
            'HR',
            'CU',
            'CW',
            'CY',
            'CZ',
            'DK',
            'DJ',
            'DM',
            'DO',
            'EC',
            'EG',
            'SV',
            'GQ',
            'ER',
            'EE',
            'ET',
            'FJ',
            'FI',
            'GF',
            'PF',
            'GA',
            'GM',
            'GE',
            'GH',
            'GR',
            'GD',
            'GP',
            'GU',
            'GT',
            'GW',
            'GY',
            'HT',
            'HN',
            'HK',
            'HU',
            'IS',
            'IN',
            'ID',
            'IR',
            'IQ',
            'IE',
            'IL',
            'IT',
            'JM',
            'JO',
            'KZ',
            'KE',
            'KI',
            'KW',
            'KG',
            'LA',
            'LV',
            'LB',
            'LS',
            'LR',
            'LY',
            'LI',
            'LT',
            'LU',
            'MK',
            'MG',
            'MW',
            'MY',
            'MV',
            'ML',
            'MT',
            'MQ',
            'MR',
            'MU',
            'MD',
            'MX',
            'MC',
            'MN',
            'ME',
            'MA',
            'MZ',
            'MM',
            'NA',
            'NR',
            'NP',
            'NL',
            'NC',
            'NZ',
            'NI',
            'NE',
            'NG',
            'KP',
            'NO',
            'OM',
            'PK',
            'PW',
            'PS',
            'PA',
            'PG',
            'PY',
            'PE',
            'PH',
            'PL',
            'PT',
            'PR',
            'QA',
            'RO',
            'RW',
            'RE',
            'KN',
            'LC',
            'VC',
            'WS',
            'SM',
            'ST',
            'SA',
            'SN',
            'RS',
            'SC',
            'SL',
            'SG',
            'SK',
            'SI',
            'SB',
            'SO',
            'ZA',
            'KR',
            'SS',
            'LK',
            'SD',
            'SR',
            'SZ',
            'SE',
            'CH',
            'SY',
            'TW',
            'TJ',
            'TZ',
            'TH',
            'TL',
            'TG',
            'TO',
            'TT',
            'TN',
            'TR',
            'TM',
            'TV',
            'UG',
            'AE',
            'UY',
            'UZ',
            'VU',
            'VE',
            'VN',
            'VA',
            'YE',
            'ZM',
            'ZW',
        ])->delete();
    }
};
