<?php

use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $now = now();

        DB::table('shipping_matrices')->insert([
            [ 'country_id' => 9, 'box_default_value' => 107.73, 'slip_default_value' => 63.55, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 10, 'box_default_value' => 63.54, 'slip_default_value' => 45.17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 11, 'box_default_value' => 84.85, 'slip_default_value' => 53.34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 12, 'box_default_value' => 77.90, 'slip_default_value' => 57.63, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 13, 'box_default_value' => 79.12, 'slip_default_value' => 51.40, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 14, 'box_default_value' => 74.98, 'slip_default_value' => 46.85, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 15, 'box_default_value' => 79.54, 'slip_default_value' => 50.02, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 16, 'box_default_value' => 65.07, 'slip_default_value' => 44.64, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 17, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 18, 'box_default_value' => 60.53, 'slip_default_value' => 42.49, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 19, 'box_default_value' => 68.24, 'slip_default_value' => 47.24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 20, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 21, 'box_default_value' => 56.57, 'slip_default_value' => 40.92, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 22, 'box_default_value' => 55.01, 'slip_default_value' => 40.91, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 23, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 24, 'box_default_value' => 49.86, 'slip_default_value' => 37.17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 25, 'box_default_value' => 81.42, 'slip_default_value' => 51.41, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 26, 'box_default_value' => 78.43, 'slip_default_value' => 49.95, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 27, 'box_default_value' => 81.78, 'slip_default_value' => 45.83, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 28, 'box_default_value' => 90.93, 'slip_default_value' => 53.27, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 29, 'box_default_value' => 77.35, 'slip_default_value' => 50.93, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 30, 'box_default_value' => 76.85, 'slip_default_value' => 49.61, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 31, 'box_default_value' => 70.05, 'slip_default_value' => 43.16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 32, 'box_default_value' => 74.41, 'slip_default_value' => 48.83, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 33, 'box_default_value' => 60.47, 'slip_default_value' => 41.80, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 34, 'box_default_value' => 81.47, 'slip_default_value' => 50.81, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 35, 'box_default_value' => 76.54, 'slip_default_value' => 49.84, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 36, 'box_default_value' => 66.54, 'slip_default_value' => 46.52, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 37, 'box_default_value' => 91.61, 'slip_default_value' => 58.23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 38, 'box_default_value' => 84.32, 'slip_default_value' => 52.97, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 39, 'box_default_value' => 101.61, 'slip_default_value' => 65.11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 40, 'box_default_value' => 108.22, 'slip_default_value' => 63.02, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 41, 'box_default_value' => 78.11, 'slip_default_value' => 48.11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 42, 'box_default_value' => 61.25, 'slip_default_value' => 45.17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 43, 'box_default_value' => 73.73, 'slip_default_value' => 44.31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 44, 'box_default_value' => 99.53, 'slip_default_value' => 58.14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 45, 'box_default_value' => 80.11, 'slip_default_value' => 50.62, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 46, 'box_default_value' => 82.16, 'slip_default_value' => 52.65, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 47, 'box_default_value' => 66.70, 'slip_default_value' => 46.53, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 48, 'box_default_value' => 93.42, 'slip_default_value' => 42.99, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 49, 'box_default_value' => 52.61, 'slip_default_value' => 39.22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 50, 'box_default_value' => 63.91, 'slip_default_value' => 46.36, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 51, 'box_default_value' => 60.86, 'slip_default_value' => 42.50, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 52, 'box_default_value' => 59.63, 'slip_default_value' => 43.77, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 53, 'box_default_value' => 78.53, 'slip_default_value' => 49.80, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 54, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 55, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 56, 'box_default_value' => 77.11, 'slip_default_value' => 48.92, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 57, 'box_default_value' => 59.44, 'slip_default_value' => 41.13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 58, 'box_default_value' => 82.16, 'slip_default_value' => 52.65, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 59, 'box_default_value' => 84.32, 'slip_default_value' => 52.97, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 60, 'box_default_value' => 86.63, 'slip_default_value' => 53.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 61, 'box_default_value' => 62.30, 'slip_default_value' => 43.63, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 62, 'box_default_value' => 77.62, 'slip_default_value' => 49.65, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 63, 'box_default_value' => 74.12, 'slip_default_value' => 51.07, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 64, 'box_default_value' => 63.54, 'slip_default_value' => 45.83, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 65, 'box_default_value' => 82.02, 'slip_default_value' => 52.31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 66, 'box_default_value' => 79.79, 'slip_default_value' => 52.05, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 67, 'box_default_value' => 76.51, 'slip_default_value' => 49.54, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 68, 'box_default_value' => 84.32, 'slip_default_value' => 50.59, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 69, 'box_default_value' => 61.44, 'slip_default_value' => 42.03, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 70, 'box_default_value' => 72.29, 'slip_default_value' => 47.92, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 71, 'box_default_value' => 55.74, 'slip_default_value' => 40.42, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 72, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 73, 'box_default_value' => 75.59, 'slip_default_value' => 49.69, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 74, 'box_default_value' => 172.67, 'slip_default_value' => 94.37, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 75, 'box_default_value' => 81.42, 'slip_default_value' => 51.41, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 76, 'box_default_value' => 86.63, 'slip_default_value' => 53.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 77, 'box_default_value' => 80.15, 'slip_default_value' => 51.51, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 78, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 79, 'box_default_value' => 82.16, 'slip_default_value' => 52.72, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 80, 'box_default_value' => 47.92, 'slip_default_value' => 34.70, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 81, 'box_default_value' => 59.89, 'slip_default_value' => 42.36, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 82, 'box_default_value' => 57.34, 'slip_default_value' => 42.16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 83, 'box_default_value' => 52.80, 'slip_default_value' => 37.16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 84, 'box_default_value' => 57.86, 'slip_default_value' => 40.05, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 85, 'box_default_value' => 81.32, 'slip_default_value' => 53.03, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 86, 'box_default_value' => 81.35, 'slip_default_value' => 59.64, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 87, 'box_default_value' => 57.47, 'slip_default_value' => 40.99, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 88, 'box_default_value' => 49.80, 'slip_default_value' => 37.18, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 89, 'box_default_value' => 57.10, 'slip_default_value' => 40.51, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 90, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 91, 'box_default_value' => 61.18, 'slip_default_value' => 41.62, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 92, 'box_default_value' => 65.91, 'slip_default_value' => 44.58, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 93, 'box_default_value' => 72.29, 'slip_default_value' => 47.92, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 94, 'box_default_value' => 75.90, 'slip_default_value' => 51.19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 95, 'box_default_value' => 56.57, 'slip_default_value' => 40.71, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 96, 'box_default_value' => 70.90, 'slip_default_value' => 47.13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 97, 'box_default_value' => 98.87, 'slip_default_value' => 57.67, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 98, 'box_default_value' => 67.48, 'slip_default_value' => 47.38, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 99, 'box_default_value' => 59.58, 'slip_default_value' => 42.28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 100, 'box_default_value' => 80.74, 'slip_default_value' => 51.45, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 101, 'box_default_value' => 80.50, 'slip_default_value' => 50.49, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 102, 'box_default_value' => 104.49, 'slip_default_value' => 61.90, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 103, 'box_default_value' => 62.19, 'slip_default_value' => 45.94, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 104, 'box_default_value' => 63.83, 'slip_default_value' => 45.16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 105, 'box_default_value' => 54.41, 'slip_default_value' => 39.37, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 106, 'box_default_value' => 81.85, 'slip_default_value' => 53.03, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 107, 'box_default_value' => 79.19, 'slip_default_value' => 50.75, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 108, 'box_default_value' => 82.97, 'slip_default_value' => 51.58, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 109, 'box_default_value' => 51.85, 'slip_default_value' => 36.55, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 110, 'box_default_value' => 66.96, 'slip_default_value' => 45.56, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 111, 'box_default_value' => 78.66, 'slip_default_value' => 51.39, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 112, 'box_default_value' => 59.56, 'slip_default_value' => 41.81, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 113, 'box_default_value' => 75.59, 'slip_default_value' => 49.69, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 114, 'box_default_value' => 84.32, 'slip_default_value' => 52.97, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 115, 'box_default_value' => 75.08, 'slip_default_value' => 49.16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 116, 'box_default_value' => 73.10, 'slip_default_value' => 48.01, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 117, 'box_default_value' => 66.94, 'slip_default_value' => 42.35, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 118, 'box_default_value' => 69.99, 'slip_default_value' => 40.08, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 119, 'box_default_value' => 93.44, 'slip_default_value' => 54.48, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 120, 'box_default_value' => 79.13, 'slip_default_value' => 48.04, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 121, 'box_default_value' => 72.29, 'slip_default_value' => 47.12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 122, 'box_default_value' => 81.61, 'slip_default_value' => 52.02, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 123, 'box_default_value' => 71.64, 'slip_default_value' => 50.63, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 124, 'box_default_value' => 74.37, 'slip_default_value' => 48.57, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 125, 'box_default_value' => 75.90, 'slip_default_value' => 53.33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 126, 'box_default_value' => 62.32, 'slip_default_value' => 44.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 127, 'box_default_value' => 52.21, 'slip_default_value' => 38.21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 128, 'box_default_value' => 79.85, 'slip_default_value' => 52.06, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 129, 'box_default_value' => 47.60, 'slip_default_value' => 30.82, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 130, 'box_default_value' => 81.42, 'slip_default_value' => 51.48, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 131, 'box_default_value' => 89.49, 'slip_default_value' => 56.23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 132, 'box_default_value' => 72.29, 'slip_default_value' => 47.92, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 133, 'box_default_value' => 85.80, 'slip_default_value' => 50.53, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 134, 'box_default_value' => 65.17, 'slip_default_value' => 47.77, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 135, 'box_default_value' => 56.57, 'slip_default_value' => 40.92, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 136, 'box_default_value' => 56.57, 'slip_default_value' => 40.92, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 137, 'box_default_value' => 172.67, 'slip_default_value' => 94.37, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 138, 'box_default_value' => 134.14, 'slip_default_value' => 81.70, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 139, 'box_default_value' => 82.34, 'slip_default_value' => 50.34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 140, 'box_default_value' => 83.93, 'slip_default_value' => 52.06, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 141, 'box_default_value' => 79.41, 'slip_default_value' => 50.18, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 142, 'box_default_value' => 80.15, 'slip_default_value' => 51.51, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 143, 'box_default_value' => 55.01, 'slip_default_value' => 40.91, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 144, 'box_default_value' => 59.72, 'slip_default_value' => 42.12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 145, 'box_default_value' => 53.31, 'slip_default_value' => 37.84, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 146, 'box_default_value' => 214.41, 'slip_default_value' => 125.13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 147, 'box_default_value' => 61.18, 'slip_default_value' => 42.01, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 148, 'box_default_value' => 60.80, 'slip_default_value' => 42.60, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 149, 'box_default_value' => 78.64, 'slip_default_value' => 50.06, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 150, 'box_default_value' => 95.55, 'slip_default_value' => 60.93, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 151, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 152, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 153, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 154, 'box_default_value' => 81.96, 'slip_default_value' => 51.80, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 155, 'box_default_value' => 60.78, 'slip_default_value' => 43.69, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 156, 'box_default_value' => 69.60, 'slip_default_value' => 47.06, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 157, 'box_default_value' => 55.62, 'slip_default_value' => 38.52, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 158, 'box_default_value' => 84.32, 'slip_default_value' => 52.97, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 159, 'box_default_value' => 74.04, 'slip_default_value' => 48.44, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 160, 'box_default_value' => 80.92, 'slip_default_value' => 54.27, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 162, 'box_default_value' => 48.43, 'slip_default_value' => 35.28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 163, 'box_default_value' => 60.37, 'slip_default_value' => 42.38, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 164, 'box_default_value' => 68.99, 'slip_default_value' => 47.14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 165, 'box_default_value' => 75.90, 'slip_default_value' => 51.53, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 166, 'box_default_value' => 132.66, 'slip_default_value' => 76.83, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 167, 'box_default_value' => 69.94, 'slip_default_value' => 47.09, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 168, 'box_default_value' => 53.96, 'slip_default_value' => 37.19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 169, 'box_default_value' => 128.64, 'slip_default_value' => 78.06, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 170, 'box_default_value' => 55.01, 'slip_default_value' => 40.91, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 171, 'box_default_value' => 76.50, 'slip_default_value' => 50.78, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 172, 'box_default_value' => 80.15, 'slip_default_value' => 48.88, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 173, 'box_default_value' => 90.63, 'slip_default_value' => 57.54, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 174, 'box_default_value' => 61.77, 'slip_default_value' => 45.37, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 175, 'box_default_value' => 54.15, 'slip_default_value' => 42.52, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 176, 'box_default_value' => 101.48, 'slip_default_value' => 60.34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 177, 'box_default_value' => 56.84, 'slip_default_value' => 38.45, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 178, 'box_default_value' => 84.54, 'slip_default_value' => 52.71, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 179, 'box_default_value' => 75.63, 'slip_default_value' => 48.60, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 180, 'box_default_value' => 53.68, 'slip_default_value' => 37.84, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 181, 'box_default_value' => 91.33, 'slip_default_value' => 60.31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 182, 'box_default_value' => 81.43, 'slip_default_value' => 50.80, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 183, 'box_default_value' => 75.90, 'slip_default_value' => 51.19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 184, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 185, 'box_default_value' => 77.81, 'slip_default_value' => 51.01, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 186, 'box_default_value' => 56.44, 'slip_default_value' => 40.45, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 187, 'box_default_value' => 97.49, 'slip_default_value' => 53.06, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 188, 'box_default_value' => 75.90, 'slip_default_value' => 48.34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 189, 'box_default_value' => 75.85, 'slip_default_value' => 48.65, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 190, 'box_default_value' => 57.63, 'slip_default_value' => 38.47, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 191, 'box_default_value' => 77.91, 'slip_default_value' => 48.76, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 192, 'box_default_value' => 71.57, 'slip_default_value' => 46.72, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 193, 'box_default_value' => 79.85, 'slip_default_value' => 51.80, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 194, 'box_default_value' => 80.28, 'slip_default_value' => 51.57, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 195, 'box_default_value' => 54.48, 'slip_default_value' => 37.33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 196, 'box_default_value' => 60.66, 'slip_default_value' => 42.89, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 197, 'box_default_value' => 113.43, 'slip_default_value' => 73.91, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 198, 'box_default_value' => 76.17, 'slip_default_value' => 49.76, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 199, 'box_default_value' => 79.87, 'slip_default_value' => 52.59, 'created_at' => $now, 'updated_at' => $now ],
            [ 'country_id' => 161, 'box_default_value' => 78.56, 'slip_default_value' => 49.81, 'created_at' => $now, 'updated_at' => $now ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('shipping_matrices')->whereIn('country_id', [
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
            115,
            116,
            117,
            118,
            119,
            120,
            121,
            122,
            123,
            124,
            125,
            126,
            127,
            128,
            129,
            130,
            131,
            132,
            133,
            134,
            135,
            136,
            137,
            138,
            139,
            140,
            141,
            142,
            143,
            144,
            145,
            146,
            147,
            148,
            149,
            150,
            151,
            152,
            153,
            154,
            155,
            156,
            157,
            158,
            159,
            160,
            162,
            163,
            164,
            165,
            166,
            167,
            168,
            169,
            170,
            171,
            172,
            173,
            174,
            175,
            176,
            177,
            178,
            179,
            180,
            181,
            182,
            183,
            184,
            185,
            186,
            187,
            188,
            189,
            190,
            191,
            192,
            193,
            194,
            195,
            196,
            197,
            198,
            199,
            161,
        ])->delete();
    }
};
