<?php

use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $now = now();

        DB::table('shipping_matrices')->insert([
            ['country_id' => DB::table('countries')->where('code', '=', 'AF')->first()->id, 'box_default_value' => 107.73, 'slip_default_value' => 63.55, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AL')->first()->id, 'box_default_value' => 63.54, 'slip_default_value' => 45.17, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'DZ')->first()->id, 'box_default_value' => 84.85, 'slip_default_value' => 53.34, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AD')->first()->id, 'box_default_value' => 77.90, 'slip_default_value' => 57.63, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AO')->first()->id, 'box_default_value' => 79.12, 'slip_default_value' => 51.40, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AG')->first()->id, 'box_default_value' => 74.98, 'slip_default_value' => 46.85, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AR')->first()->id, 'box_default_value' => 79.54, 'slip_default_value' => 50.02, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AM')->first()->id, 'box_default_value' => 65.07, 'slip_default_value' => 44.64, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AW')->first()->id, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AT')->first()->id, 'box_default_value' => 60.53, 'slip_default_value' => 42.49, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AZ')->first()->id, 'box_default_value' => 68.24, 'slip_default_value' => 47.24, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BS')->first()->id, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BH')->first()->id, 'box_default_value' => 56.57, 'slip_default_value' => 40.92, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BD')->first()->id, 'box_default_value' => 55.01, 'slip_default_value' => 40.91, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BB')->first()->id, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BE')->first()->id, 'box_default_value' => 49.86, 'slip_default_value' => 37.17, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BZ')->first()->id, 'box_default_value' => 81.42, 'slip_default_value' => 51.41, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BJ')->first()->id, 'box_default_value' => 78.43, 'slip_default_value' => 49.95, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BT')->first()->id, 'box_default_value' => 81.78, 'slip_default_value' => 45.83, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BO')->first()->id, 'box_default_value' => 90.93, 'slip_default_value' => 53.27, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BA')->first()->id, 'box_default_value' => 77.35, 'slip_default_value' => 50.93, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BW')->first()->id, 'box_default_value' => 76.85, 'slip_default_value' => 49.61, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BR')->first()->id, 'box_default_value' => 70.05, 'slip_default_value' => 43.16, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BN')->first()->id, 'box_default_value' => 74.41, 'slip_default_value' => 48.83, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BG')->first()->id, 'box_default_value' => 60.47, 'slip_default_value' => 41.80, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BF')->first()->id, 'box_default_value' => 81.47, 'slip_default_value' => 50.81, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'BI')->first()->id, 'box_default_value' => 76.54, 'slip_default_value' => 49.84, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KH')->first()->id, 'box_default_value' => 66.54, 'slip_default_value' => 46.52, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CM')->first()->id, 'box_default_value' => 91.61, 'slip_default_value' => 58.23, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CV')->first()->id, 'box_default_value' => 84.32, 'slip_default_value' => 52.97, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CF')->first()->id, 'box_default_value' => 101.61, 'slip_default_value' => 65.11, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TD')->first()->id, 'box_default_value' => 108.22, 'slip_default_value' => 63.02, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CL')->first()->id, 'box_default_value' => 78.11, 'slip_default_value' => 48.11, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CN')->first()->id, 'box_default_value' => 61.25, 'slip_default_value' => 45.17, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CO')->first()->id, 'box_default_value' => 73.73, 'slip_default_value' => 44.31, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KM')->first()->id, 'box_default_value' => 99.53, 'slip_default_value' => 58.14, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CG')->first()->id, 'box_default_value' => 80.11, 'slip_default_value' => 50.62, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CR')->first()->id, 'box_default_value' => 82.16, 'slip_default_value' => 52.65, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'HR')->first()->id, 'box_default_value' => 66.70, 'slip_default_value' => 46.53, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CU')->first()->id, 'box_default_value' => 93.42, 'slip_default_value' => 42.99, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CW')->first()->id, 'box_default_value' => 52.61, 'slip_default_value' => 39.22, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CY')->first()->id, 'box_default_value' => 63.91, 'slip_default_value' => 46.36, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CZ')->first()->id, 'box_default_value' => 60.86, 'slip_default_value' => 42.50, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'DK')->first()->id, 'box_default_value' => 59.63, 'slip_default_value' => 43.77, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'DJ')->first()->id, 'box_default_value' => 78.53, 'slip_default_value' => 49.80, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'DM')->first()->id, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'DO')->first()->id, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'EC')->first()->id, 'box_default_value' => 77.11, 'slip_default_value' => 48.92, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'EG')->first()->id, 'box_default_value' => 59.44, 'slip_default_value' => 41.13, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SV')->first()->id, 'box_default_value' => 82.16, 'slip_default_value' => 52.65, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GQ')->first()->id, 'box_default_value' => 84.32, 'slip_default_value' => 52.97, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ER')->first()->id, 'box_default_value' => 86.63, 'slip_default_value' => 53.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'EE')->first()->id, 'box_default_value' => 62.30, 'slip_default_value' => 43.63, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ET')->first()->id, 'box_default_value' => 77.62, 'slip_default_value' => 49.65, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'FJ')->first()->id, 'box_default_value' => 74.12, 'slip_default_value' => 51.07, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'FI')->first()->id, 'box_default_value' => 63.54, 'slip_default_value' => 45.83, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GF')->first()->id, 'box_default_value' => 82.02, 'slip_default_value' => 52.31, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PF')->first()->id, 'box_default_value' => 79.79, 'slip_default_value' => 52.05, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GA')->first()->id, 'box_default_value' => 76.51, 'slip_default_value' => 49.54, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GM')->first()->id, 'box_default_value' => 84.32, 'slip_default_value' => 50.59, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GE')->first()->id, 'box_default_value' => 61.44, 'slip_default_value' => 42.03, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GH')->first()->id, 'box_default_value' => 72.29, 'slip_default_value' => 47.92, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GR')->first()->id, 'box_default_value' => 55.74, 'slip_default_value' => 40.42, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GD')->first()->id, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GP')->first()->id, 'box_default_value' => 75.59, 'slip_default_value' => 49.69, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GU')->first()->id, 'box_default_value' => 172.67, 'slip_default_value' => 94.37, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GT')->first()->id, 'box_default_value' => 81.42, 'slip_default_value' => 51.41, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GW')->first()->id, 'box_default_value' => 86.63, 'slip_default_value' => 53.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'GY')->first()->id, 'box_default_value' => 80.15, 'slip_default_value' => 51.51, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'HT')->first()->id, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'HN')->first()->id, 'box_default_value' => 82.16, 'slip_default_value' => 52.72, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'HK')->first()->id, 'box_default_value' => 47.92, 'slip_default_value' => 34.70, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'HU')->first()->id, 'box_default_value' => 59.89, 'slip_default_value' => 42.36, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'IS')->first()->id, 'box_default_value' => 57.34, 'slip_default_value' => 42.16, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'IN')->first()->id, 'box_default_value' => 52.80, 'slip_default_value' => 37.16, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ID')->first()->id, 'box_default_value' => 57.86, 'slip_default_value' => 40.05, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'IR')->first()->id, 'box_default_value' => 81.32, 'slip_default_value' => 53.03, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'IQ')->first()->id, 'box_default_value' => 81.35, 'slip_default_value' => 59.64, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'IE')->first()->id, 'box_default_value' => 57.47, 'slip_default_value' => 40.99, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'IL')->first()->id, 'box_default_value' => 49.80, 'slip_default_value' => 37.18, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'IT')->first()->id, 'box_default_value' => 57.10, 'slip_default_value' => 40.51, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'JM')->first()->id, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'JO')->first()->id, 'box_default_value' => 61.18, 'slip_default_value' => 41.62, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KZ')->first()->id, 'box_default_value' => 65.91, 'slip_default_value' => 44.58, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KE')->first()->id, 'box_default_value' => 72.29, 'slip_default_value' => 47.92, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KI')->first()->id, 'box_default_value' => 75.90, 'slip_default_value' => 51.19, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KW')->first()->id, 'box_default_value' => 56.57, 'slip_default_value' => 40.71, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KG')->first()->id, 'box_default_value' => 70.90, 'slip_default_value' => 47.13, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LA')->first()->id, 'box_default_value' => 98.87, 'slip_default_value' => 57.67, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LV')->first()->id, 'box_default_value' => 67.48, 'slip_default_value' => 47.38, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LB')->first()->id, 'box_default_value' => 59.58, 'slip_default_value' => 42.28, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LS')->first()->id, 'box_default_value' => 80.74, 'slip_default_value' => 51.45, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LR')->first()->id, 'box_default_value' => 80.50, 'slip_default_value' => 50.49, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LY')->first()->id, 'box_default_value' => 104.49, 'slip_default_value' => 61.90, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LI')->first()->id, 'box_default_value' => 62.19, 'slip_default_value' => 45.94, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LT')->first()->id, 'box_default_value' => 63.83, 'slip_default_value' => 45.16, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LU')->first()->id, 'box_default_value' => 54.41, 'slip_default_value' => 39.37, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MK')->first()->id, 'box_default_value' => 81.85, 'slip_default_value' => 53.03, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MG')->first()->id, 'box_default_value' => 79.19, 'slip_default_value' => 50.75, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MW')->first()->id, 'box_default_value' => 82.97, 'slip_default_value' => 51.58, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MY')->first()->id, 'box_default_value' => 51.85, 'slip_default_value' => 36.55, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MV')->first()->id, 'box_default_value' => 66.96, 'slip_default_value' => 45.56, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ML')->first()->id, 'box_default_value' => 78.66, 'slip_default_value' => 51.39, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MT')->first()->id, 'box_default_value' => 59.56, 'slip_default_value' => 41.81, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MQ')->first()->id, 'box_default_value' => 75.59, 'slip_default_value' => 49.69, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MR')->first()->id, 'box_default_value' => 84.32, 'slip_default_value' => 52.97, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MU')->first()->id, 'box_default_value' => 75.08, 'slip_default_value' => 49.16, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MD')->first()->id, 'box_default_value' => 73.10, 'slip_default_value' => 48.01, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MX')->first()->id, 'box_default_value' => 66.94, 'slip_default_value' => 42.35, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MC')->first()->id, 'box_default_value' => 69.99, 'slip_default_value' => 40.08, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MN')->first()->id, 'box_default_value' => 93.44, 'slip_default_value' => 54.48, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ME')->first()->id, 'box_default_value' => 79.13, 'slip_default_value' => 48.04, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MA')->first()->id, 'box_default_value' => 72.29, 'slip_default_value' => 47.12, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MZ')->first()->id, 'box_default_value' => 81.61, 'slip_default_value' => 52.02, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'MM')->first()->id, 'box_default_value' => 71.64, 'slip_default_value' => 50.63, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NA')->first()->id, 'box_default_value' => 74.37, 'slip_default_value' => 48.57, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NR')->first()->id, 'box_default_value' => 75.90, 'slip_default_value' => 53.33, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NP')->first()->id, 'box_default_value' => 62.32, 'slip_default_value' => 44.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NL')->first()->id, 'box_default_value' => 52.21, 'slip_default_value' => 38.21, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NC')->first()->id, 'box_default_value' => 79.85, 'slip_default_value' => 52.06, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NZ')->first()->id, 'box_default_value' => 47.60, 'slip_default_value' => 30.82, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NI')->first()->id, 'box_default_value' => 81.42, 'slip_default_value' => 51.48, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NE')->first()->id, 'box_default_value' => 89.49, 'slip_default_value' => 56.23, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NG')->first()->id, 'box_default_value' => 72.29, 'slip_default_value' => 47.92, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KP')->first()->id, 'box_default_value' => 85.80, 'slip_default_value' => 50.53, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'NO')->first()->id, 'box_default_value' => 65.17, 'slip_default_value' => 47.77, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'OM')->first()->id, 'box_default_value' => 56.57, 'slip_default_value' => 40.92, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PK')->first()->id, 'box_default_value' => 56.57, 'slip_default_value' => 40.92, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PW')->first()->id, 'box_default_value' => 172.67, 'slip_default_value' => 94.37, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PS')->first()->id, 'box_default_value' => 134.14, 'slip_default_value' => 81.70, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PA')->first()->id, 'box_default_value' => 82.34, 'slip_default_value' => 50.34, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PG')->first()->id, 'box_default_value' => 83.93, 'slip_default_value' => 52.06, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PY')->first()->id, 'box_default_value' => 79.41, 'slip_default_value' => 50.18, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PE')->first()->id, 'box_default_value' => 80.15, 'slip_default_value' => 51.51, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PH')->first()->id, 'box_default_value' => 55.01, 'slip_default_value' => 40.91, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PL')->first()->id, 'box_default_value' => 59.72, 'slip_default_value' => 42.12, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PT')->first()->id, 'box_default_value' => 53.31, 'slip_default_value' => 37.84, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'PR')->first()->id, 'box_default_value' => 214.41, 'slip_default_value' => 125.13, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'QA')->first()->id, 'box_default_value' => 61.18, 'slip_default_value' => 42.01, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'RO')->first()->id, 'box_default_value' => 60.80, 'slip_default_value' => 42.60, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'RW')->first()->id, 'box_default_value' => 78.64, 'slip_default_value' => 50.06, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'RE')->first()->id, 'box_default_value' => 95.55, 'slip_default_value' => 60.93, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KN')->first()->id, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LC')->first()->id, 'box_default_value' => 75.72, 'slip_default_value' => 49.96, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'VC')->first()->id, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'WS')->first()->id, 'box_default_value' => 81.96, 'slip_default_value' => 51.80, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SM')->first()->id, 'box_default_value' => 60.78, 'slip_default_value' => 43.69, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ST')->first()->id, 'box_default_value' => 69.60, 'slip_default_value' => 47.06, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SA')->first()->id, 'box_default_value' => 55.62, 'slip_default_value' => 38.52, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SN')->first()->id, 'box_default_value' => 84.32, 'slip_default_value' => 52.97, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'RS')->first()->id, 'box_default_value' => 74.04, 'slip_default_value' => 48.44, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SC')->first()->id, 'box_default_value' => 80.92, 'slip_default_value' => 54.27, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SG')->first()->id, 'box_default_value' => 48.43, 'slip_default_value' => 35.28, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SK')->first()->id, 'box_default_value' => 60.37, 'slip_default_value' => 42.38, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SI')->first()->id, 'box_default_value' => 68.99, 'slip_default_value' => 47.14, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SB')->first()->id, 'box_default_value' => 75.90, 'slip_default_value' => 51.53, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SO')->first()->id, 'box_default_value' => 132.66, 'slip_default_value' => 76.83, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ZA')->first()->id, 'box_default_value' => 69.94, 'slip_default_value' => 47.09, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'KR')->first()->id, 'box_default_value' => 53.96, 'slip_default_value' => 37.19, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SS')->first()->id, 'box_default_value' => 128.64, 'slip_default_value' => 78.06, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'LK')->first()->id, 'box_default_value' => 55.01, 'slip_default_value' => 40.91, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SD')->first()->id, 'box_default_value' => 76.50, 'slip_default_value' => 50.78, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SR')->first()->id, 'box_default_value' => 80.15, 'slip_default_value' => 48.88, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SZ')->first()->id, 'box_default_value' => 90.63, 'slip_default_value' => 57.54, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SE')->first()->id, 'box_default_value' => 61.77, 'slip_default_value' => 45.37, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'CH')->first()->id, 'box_default_value' => 54.15, 'slip_default_value' => 42.52, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SY')->first()->id, 'box_default_value' => 101.48, 'slip_default_value' => 60.34, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TW')->first()->id, 'box_default_value' => 56.84, 'slip_default_value' => 38.45, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TJ')->first()->id, 'box_default_value' => 84.54, 'slip_default_value' => 52.71, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TZ')->first()->id, 'box_default_value' => 75.63, 'slip_default_value' => 48.60, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TH')->first()->id, 'box_default_value' => 53.68, 'slip_default_value' => 37.84, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TL')->first()->id, 'box_default_value' => 91.33, 'slip_default_value' => 60.31, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TG')->first()->id, 'box_default_value' => 81.43, 'slip_default_value' => 50.80, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TO')->first()->id, 'box_default_value' => 75.90, 'slip_default_value' => 51.19, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TT')->first()->id, 'box_default_value' => 74.98, 'slip_default_value' => 48.73, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TN')->first()->id, 'box_default_value' => 77.81, 'slip_default_value' => 51.01, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TR')->first()->id, 'box_default_value' => 56.44, 'slip_default_value' => 40.45, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TM')->first()->id, 'box_default_value' => 97.49, 'slip_default_value' => 53.06, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'TV')->first()->id, 'box_default_value' => 75.90, 'slip_default_value' => 48.34, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'UG')->first()->id, 'box_default_value' => 75.85, 'slip_default_value' => 48.65, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'AE')->first()->id, 'box_default_value' => 57.63, 'slip_default_value' => 38.47, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'UY')->first()->id, 'box_default_value' => 77.91, 'slip_default_value' => 48.76, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'UZ')->first()->id, 'box_default_value' => 71.57, 'slip_default_value' => 46.72, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'VU')->first()->id, 'box_default_value' => 79.85, 'slip_default_value' => 51.80, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'VE')->first()->id, 'box_default_value' => 80.28, 'slip_default_value' => 51.57, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'VN')->first()->id, 'box_default_value' => 54.48, 'slip_default_value' => 37.33, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'VA')->first()->id, 'box_default_value' => 60.66, 'slip_default_value' => 42.89, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'YE')->first()->id, 'box_default_value' => 113.43, 'slip_default_value' => 73.91, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ZM')->first()->id, 'box_default_value' => 76.17, 'slip_default_value' => 49.76, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'ZW')->first()->id, 'box_default_value' => 79.87, 'slip_default_value' => 52.59, 'created_at' => $now, 'updated_at' => $now],
            ['country_id' => DB::table('countries')->where('code', '=', 'SL')->first()->id, 'box_default_value' => 78.56, 'slip_default_value' => 49.81, 'created_at' => $now, 'updated_at' => $now],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('shipping_matrices')->whereIn('country_id',
            DB::table('countries')->whereIn('code', [
                'AF',
                'AL',
                'DZ',
                'AD',
                'AO',
                'AG',
                'AR',
                'AM',
                'AW',
                'AT',
                'AZ',
                'BS',
                'BH',
                'BD',
                'BB',
                'BE',
                'BZ',
                'BJ',
                'BT',
                'BO',
                'BA',
                'BW',
                'BR',
                'BN',
                'BG',
                'BF',
                'BI',
                'KH',
                'CM',
                'CV',
                'CF',
                'TD',
                'CL',
                'CN',
                'CO',
                'KM',
                'CG',
                'CR',
                'HR',
                'CU',
                'CW',
                'CY',
                'CZ',
                'DK',
                'DJ',
                'DM',
                'DO',
                'EC',
                'EG',
                'SV',
                'GQ',
                'ER',
                'EE',
                'ET',
                'FJ',
                'FI',
                'GF',
                'PF',
                'GA',
                'GM',
                'GE',
                'GH',
                'GR',
                'GD',
                'GP',
                'GU',
                'GT',
                'GW',
                'GY',
                'HT',
                'HN',
                'HK',
                'HU',
                'IS',
                'IN',
                'ID',
                'IR',
                'IQ',
                'IE',
                'IL',
                'IT',
                'JM',
                'JO',
                'KZ',
                'KE',
                'KI',
                'KW',
                'KG',
                'LA',
                'LV',
                'LB',
                'LS',
                'LR',
                'LY',
                'LI',
                'LT',
                'LU',
                'MK',
                'MG',
                'MW',
                'MY',
                'MV',
                'ML',
                'MT',
                'MQ',
                'MR',
                'MU',
                'MD',
                'MX',
                'MC',
                'MN',
                'ME',
                'MA',
                'MZ',
                'MM',
                'NA',
                'NR',
                'NP',
                'NL',
                'NC',
                'NZ',
                'NI',
                'NE',
                'NG',
                'KP',
                'NO',
                'OM',
                'PK',
                'PW',
                'PS',
                'PA',
                'PG',
                'PY',
                'PE',
                'PH',
                'PL',
                'PT',
                'PR',
                'QA',
                'RO',
                'RW',
                'RE',
                'KN',
                'LC',
                'VC',
                'WS',
                'SM',
                'ST',
                'SA',
                'SN',
                'RS',
                'SC',
                'SG',
                'SK',
                'SI',
                'SB',
                'SO',
                'ZA',
                'KR',
                'SS',
                'LK',
                'SD',
                'SR',
                'SZ',
                'SE',
                'CH',
                'SY',
                'TW',
                'TJ',
                'TZ',
                'TH',
                'TL',
                'TG',
                'TO',
                'TT',
                'TN',
                'TR',
                'TM',
                'TV',
                'UG',
                'AE',
                'UY',
                'UZ',
                'VU',
                'VE',
                'VN',
                'VA',
                'YE',
                'ZM',
                'ZW',
                'SL',
            ])->pluck('id')->toArray()
        )->delete();
    }
};
